apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1jod
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1jod
    app.kubernetes.io/part-of: tkrw-pr712-0075-0062-app
  name: devfile-sample-1jod
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1jod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1jod
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0062-tenant/tkrw-pr712-0075-0062-app/devfile-sample-1jod@sha256:d74976279e5446146c99a314092bcd0d921e2aa19ddc1b6fccc9a79b383b4884
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
